### ISSUE TITLE
Add new line on every translation after normalize

### ISSUE THREAD

**Issue by ivan-gaydamakin** [FlineDev/BartyCrouch#251]
## Problem Statement
I have file like:
```
"account" = "Account";
"top" = "Top";
"movie" = "Movie";

```

When I made "normalize" I got:
```
"account" = "Account";

"top" = "Top";

"movie" = "Movie";

```

## Suggested Solution
Maybe add some param for "normalize" step, like "with_new_line=false"?

**Comment by Jeehut** [comment]
@ivan-gaydamakin Thank you for that suggestion. That's actually a nice idea and should be easy enough to implement. Do you want to tackle the implementation yourself, maybe? You'd just need to add a new param [here](https://github.com/FlineDev/BartyCrouch/blob/main/Sources/BartyCrouchKit/OldCommandLine/CommandLineActor.swift#L139-L147), pass that down to the `StringsFileUpdater` and adjust the separator [in this line](https://github.com/FlineDev/BartyCrouch/blob/main/Sources/BartyCrouchKit/FileHandling/StringsFileUpdater.swift#L418)  from `"\n\n"` to `"\n"` when your option is active.

I might have a look into that myself, too, but I can't promise you any timeline right now ...
