### ISSUE TITLE
[Feat] Support for modular application

### ISSUE THREAD

**Issue by MaxAdamyan** [FlineDev/BartyCrouch#268]
## Problem Statement

I have multi-modular application. Modules are defined as separate swift packages. I want to have a possibility to collect localizable strings from each module in a `Localizable.strings` of the same module.

## Suggested Solution

A possible solution will be, to have a possibility to define more than on of each task. E.g. `code`: we can have one `code` task for main application target, and several `code` tasks for each module, with its own `Localizable.strings` file and settings.

## Additional Considerations

I have tried to have both `Localizable.strings` files paths in `localizablePaths` of `.bartycrouch.toml`. But it just duplicates all the strings from all modules.

**Comment by Jeehut** [comment]
Have you tried creating multiple `.bartycrouch.toml` files, one for each module? And if you use the build-script, just make sure to repeat the commands for each `--path` (or `-p`) so they all get updated properly. This should be possible, tell me if you need any further assistance.

**Comment by MaxAdamyan** [comment]
@Jeehut thank you very much. I just run multiple `update` commands for each module in the respective directory.

**Comment by Jeehut** [comment]
@MaxAdamyan Sounds great. If this resolves the issue for you, please close this ticket. Else, let me know how I can help.

**Comment by Jeehut** [comment]
As there's no answer here and I believe that the last message can be interpreted as "the suggested workaround worked for me", I'm going to close this until someone comments that the workaround actually doesn't work.
