### ISSUE TITLE
[Question/Bug] : .bartycrouch.toml permission errors on dependent test build

### ISSUE THREAD

**Issue by thejeff77** [FlineDev/BartyCrouch#283]
## Steps to Reproduce:

I have a "Project" and also a scheme "ProjectTests" which depends on Project. 

Have you ever seen it where "Project" builds fine, but "ProjectTests" has the error below?

```
Error: The file “.bartycrouch.toml” couldn’t be opened because you don’t have permission to view it.
Error: The file “.bartycrouch.toml” couldn’t be opened because you don’t have permission to view it.
```

This was a working project at some point, haven't opened it in a long time, but I'm working myself through a variety of weird build errors, this being one of them.

What I've tried:
- chmod 777 to the file, it has full permissions..
- restart, clear build cache, derived data, etc.

1. Dunno. Waited a long time since I had a working project

## Expected Behavior:

No permissions errors on build

## Environment

<details>
<summary>Show environment details</summary>

</details>

**Comment by Jeehut** [comment]
@thejeff77 Sounds like a new access control security feature in macOS Sonoma that probably affects other CLI tools, too.

**Comment by thejeff77** [comment]
@Jeehut gotcha, thanks for the info. Curious, do you know any fixes for this?

**Comment by Jeehut** [comment]
I've run into this with another tool but couldn't find a quick fix. Didn't search long though, there might be one.

**Comment by Dzionis** [comment]
Hello, do you have a solution?
I have the same problem. When I add .bartycrouch.toml to the project I have the same error. 
When I delete this file, I get error Localizable.strings not found. File exists in project and even has few languages.

In previous project everything works fine.

**Comment by Dzionis** [comment]
@thejeff77 @Jeehut Do you find any solution?

**Comment by thejeff77** [comment]
@Dzionis and @Jeehut - Yes, set "user script sandboxing" to NO in build settings.

Should probably be added to the README.

**Comment by Jeehut** [comment]
@thejeff77 Done, added it in README. 👍

**Comment by Jeehut** [comment]
@thejeff77 Done, added it in README. 👍
